### ISSUE TITLE
Rectangular tile index incorrect when not a multiple of tile width/height

### ISSUE THREAD

**Issue by timkurvers** [Trouv/bevy_ecs_ldtk#105]
This seemingly occurs when a [rectangle of tiles](https://github.com/deepnight/ldtk/issues/533) is chosen for an entity, and the offset of this rectangle is not a multiple of the tile width or height.

Most likely a floor-vs-ceil issue in [`#[sprite_sheet_bundle]`](https://github.com/Trouv/bevy_ecs_ldtk/blob/main/src/utils.rs#L287-L289), but I am not super familiar with the intricacies involved here.

More than happy to provide a reproduction case if required.

---

Compare this LDtk screenshot:

<img width="400" alt="Screenshot 2022-08-07 at 10 14 01" src="https://user-images.githubusercontent.com/378235/183282123-767675b3-8f72-4309-ae69-c4c1ebc36ebb.png">

With the `bevy_ecs_ldtk` rendered result (both entities on the right are off by one column and row respectively):

<img width="400" alt="Screenshot 2022-08-07 at 10 14 15" src="https://user-images.githubusercontent.com/378235/183282128-2af8f019-008f-4787-b34b-9916f225d571.png">

**Comment by Zak0749** [comment]
For your tilesets are you using any spacing/padding? That causes me issues sometimes

**Comment by timkurvers** [comment]
> For your tilesets are you using any spacing/padding? That causes me issues sometimes

No spacing/padding on the tileset.

Only difference between the entities is the rectangle selection (as far as I can tell):

<img width="296" alt="Screenshot 2022-08-07 at 10 13 38" src="https://user-images.githubusercontent.com/378235/183282811-33a9b5ec-19af-4183-a2d4-1ef04dbca6fa.png" align="left">

<img width="298" alt="Screenshot 2022-08-07 at 10 13 50" src="https://user-images.githubusercontent.com/378235/183282815-dabbcb23-7bb1-4723-9ac4-c10db6618ef9.png" align="left">

**Comment by Trouv** [comment]
Thanks for the issue. I don't think using selecting a rectangle for the entity visual was a use case I was targeting when writing this plugin, so it makes sense that it doesn't quite work. I'm actually kind of surprised that it almost works now.

I agree, it's almost definitely a ceiling vs floor issue.

Since this isn't explicitly supported, I've changed this from a bug to an enhancement, and removed it from the 0.4 milestone.
