### ISSUE TITLE
oops wrong place sorry

### ISSUE THREAD

**Issue by IssaackG** [Trouv/bevy_ecs_ldtk#114]
![issue](https://user-images.githubusercontent.com/65767316/187490913-0f6ce704-bae3-44e3-9bfd-2c368bd63853.PNG)
I'm making a terraria clone using a mesh however if I change the orthographic projection to zoom, then pixels from neighbouring tiles in the sprite sheet appear and it becomes blurry.

Here is the sprite sheet (its temporary).
![issue2](https://user-images.githubusercontent.com/65767316/187491397-d74ed80f-ece6-4e13-9561-a23c98837bb8.PNG)

**Comment by Trouv** [comment]
No worries!
