### ISSUE TITLE
Critical Memory Leak and Segfault when Using Autolayers

### ISSUE THREAD

**Issue by zicklag** [Trouv/bevy_ecs_ldtk#118]
When running a demo map with auto-layers on Linux Ubuntu 20.04 I'm getting a memory leak that will rapidly expand to using 8GB+ of memory in less than 30 seconds before finally segfaulting.

There's nothing obvious in the logs other than the fact that it happens immediately after `LDtk asset creation detected.` and nothing happens after that.

[demo-map.zip](https://github.com/Trouv/bevy_ecs_ldtk/files/9716896/demo-map.zip)
[trace_log.txt](https://github.com/Trouv/bevy_ecs_ldtk/files/9716915/trace_log.txt)

**Comment by Trouv** [comment]
Thanks for reporting this. I am able to reproduce this issue. I'm guessing this is a bug that's specific to "Rectangle of tiles" rules. Disabling the "Stamps" rule group of the "Walls" layer allows the level to load fine.

**Comment by Trouv** [comment]
Looking into this. It only happens with the "Rectangle of Tiles" rules when the rectangles overflow the bounds of the level.

**Comment by Trouv** [comment]
Could you try using the branch `fix/out-of-bounds-tiles`?

**Comment by zicklag** [comment]
Yep, that fixes it!

**Comment by zicklag** [comment]
Thanks!
