### ISSUE TITLE
Deprecation of Heron

### ISSUE THREAD

**Issue by CashWasabi** [Trouv/bevy_ecs_ldtk#123]
Hey there,
I noticed yesterday that [heron](https://github.com/jcornaz/heron) is going to be abandoned and will not have support for `bevy 0.9`.
Do you think it makes sense to translate the platformer example to [bevy_rapier](https://github.com/dimforge/bevy_rapier)?

**Comment by Trouv** [comment]
Yes, we'll definitely need to do this before 0.9

**Comment by CashWasabi** [comment]
I ported my small 2D side-scroller project to `bevy_rapier2d` recently. 
I could also do a port for the platformer example if it would help. :)

**Comment by Trouv** [comment]
That would be very appreciated, as with any other contribution! I'll get to it eventually if not though

**Comment by CashWasabi** [comment]
I created a [PR](https://github.com/Trouv/bevy_ecs_ldtk/pull/127) sumarizing my changes. If there's an issue I can of course change things up a bit. I had a small issues with the `GroundSensor` sometimes not working though. I'm looking into that but everything else should work as expected.
