### ISSUE TITLE
Update to new renderer

### ISSUE THREAD

**Issue by Trouv** [Trouv/bevy_ecs_ldtk#16]
Might be a good idea to try out the `new-renderer` branch of `bevy_ecs_tilemap` as well as updating the `bevy` revision to see how the new renderer may affect this plugin.

**Comment by StarArawn** [comment]
Hi! I just saw this project exists. It's worth pointing out that `bevy_ecs_tilemap`'s `new-renderer` branch is merged into main now. Also if you need any help feel free to ping me on discord! 👍

**Comment by Trouv** [comment]
Oh hey! I actually just noticed that today and was doing that update as you commented. Thanks for following up!
