### ISSUE TITLE
Levels not rendered correctly on wasm

### ISSUE THREAD

**Issue by lewiszlw** [Trouv/bevy_ecs_ldtk#182]
Hi, 

I'm using `bevy_ecs_ldtk` 0.6 to load .ldtk file. It works well on native, but not on wasm. I didn't meet this issue in my last game (using bevy_ecs_ldtk 0.5), not sure it's a bug or something I miss.

wasm
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/17514693/232549503-5823bf26-9ccf-4cc3-bdb6-031802596ff4.png">

native
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/17514693/232549564-7c2df542-a954-483a-bbe7-0ef22128ebf5.png">

Reproduce: 
1. clone https://github.com/NightsWatchGames/celeste
2. `rustup target install wasm32-unknown-unknown`
3. `cargo install wasm-server-runner`
4. `cargo run --target wasm32-unknown-unknown`
5. open the link in browser

**Comment by Trouv** [comment]
Just to make sure - are you using the `atlas` feature? 
```sh
$ cargo run --target wasm32-unknown-unknown --features bevy_ecs_ldtk/atlas
```

**Comment by lewiszlw** [comment]
Seems yes. It works after adding atlas feature. Thanks!
