### ISSUE TITLE
Pixel art tile textures are blurry - where can you set texture sampling options? 

### ISSUE THREAD

**Issue by cc959** [Trouv/bevy_ecs_ldtk#196]
![image](https://github.com/Trouv/bevy_ecs_ldtk/assets/59772837/fe004dbf-3d32-407e-84a7-5d6b7ff4f182)

**Comment by Trouv** [comment]
You likely need to set it on the bevy `ImagePlugin`. If you're using default plugins, you can do so like this:
```rust
App::new()
    .add_plugins(DefaultPlugins.set(ImagePlugin::default_nearest()))
```
