### ISSUE TITLE
Incompatible with Bevy 0.11

### ISSUE THREAD

**Issue by BernardIgiri** [Trouv/bevy_ecs_ldtk#202]
I was experimenting with with this package while using Bevy 0.11 when Cargo Clippy reported the following error:
```
the trait `bevy::prelude::Resource` is not implemented for `bevy_ecs_ldtk::LdtkSettings`
    |
    = help: the following other types implement trait `bevy::prelude::Resource`:
              bevy::a11y::AccessibilityRequested
              bevy::a11y::Focus
              bevy::app::MainScheduleOrder
              bevy::core::FrameCount
              bevy::core_pipeline::blit::BlitPipeline
              bevy::core_pipeline::bloom::downsampling_pipeline::BloomDownsamplingPipeline
              bevy::core_pipeline::bloom::upsampling_pipeline::BloomUpsamplingPipeline
              bevy::core_pipeline::contrast_adaptive_sharpening::CASPipeline
            and 111 others
note: required by a bound in `bevy::prelude::App::insert_resource`
```
I see that the bevy_ecs_tilemap dependency has a PR for fixing it's Bevy 0.11 compatibility: https://github.com/StarArawn/bevy_ecs_tilemap/pull/440

I also see that Rapier just needs to be upgraded to version 0.22.0.

A number of other changes will also be necessary to comply with the changes in Bevy 0.11
https://bevyengine.org/news/bevy-0-11/

While I'm still learning Bevy, I am available if you need help with this upgrade. Just let me know. Good luck!

**Comment by Trouv** [comment]
Thanks for the offer! Some time soon I will perform this upgrade if nobody else does, but you're right, `bevy_ecs_tilemap` is a pretty strict blocker for our upgrading. Sometimes it takes a couple weeks after the bevy release for this plugin to release.

If you want to try upgrading it yourself though, you need only make a branch that changes the `Cargo.toml` to point to that `bevy_ecs_tilemap` PR as a git dependency and then basically follow the bevy 0.10-0.11 migration guide. Once you have that, I'd be happy to receive it as a contribution, and you can also point to your branch of `bevy_ecs_ldtk` in whatever project you're working on to use it as well.

I'm not tasking you with this, but you are welcome to do it if you want! Like I said, if nobody else does by the time that `bevy_ecs_tilemap` PR is merged than I will work on it too, so no pressure.
