### ISSUE TITLE
Add `LayerMetadata` entities for Entity layers

### ISSUE THREAD

**Issue by tsalkenov** [Trouv/bevy_ecs_ldtk#224]
i used LayerMetadata to edit transforms of other types of layers. But it seems like entity layer doesn't have LayerMetadata or i may be wrong

**Comment by Trouv** [comment]
You're right, if doesn't at the moment. For now entities are children of the level entity. I've been meaning to give entity layers their own entity as well but haven't gotten around to it yet, sorry about that. For now you might just need to manually edit the z value on the individual entities instead.

**Comment by tsalkenov** [comment]
I'm trying create collider the size of the whole level but on lower z index to make gravity push player against map surface. but player just falls through collider because of the same z index, i guess i will just lower background. Should i keep the issue open?

**Comment by Trouv** [comment]
Sure, it's a little related to #116, but I think I'll dedicate this issue to "Add LayerMetadata entities for Entity Layers" specifically. I hope you don't mind if I update the issue title accordingly.
