### ISSUE TITLE
LDTK region strange in runtime

### ISSUE THREAD

**Issue by darkautism** [Trouv/bevy_ecs_ldtk#267]
```
pub struct PlayerChatBundle {
    #[with(player_chat_collider)]
    collider: Collider,
    #[with(player_chat_active_events)]
    active_events: ActiveEvents,
    sensor: Sensor,
    #[with(Dialogue::from_field)]
    pub value: Dialogue,
}
fn player_chat_active_events(_: &EntityInstance) -> ActiveEvents {
    ActiveEvents::COLLISION_EVENTS
}
fn player_chat_collider(ei: &EntityInstance) -> Collider {
    info!("{:?}, {:?}", ei.grid.x as f32 / 2., ei.grid.y as f32 / 2.);
    info!("{:?}, {:?}", ei.height as f32 / 2., ei.width as f32 / 2.);
    Collider::cuboid(1. , 1.)
}

In main.rs:
            .register_ldtk_entity::<PlayerChatBundle>("PlayerChat")
```

![image](https://github.com/Trouv/bevy_ecs_ldtk/assets/3898040/b0d889e6-705b-49e6-8877-2258d520e438)
![image](https://github.com/Trouv/bevy_ecs_ldtk/assets/3898040/dcbb6860-df3c-4947-86fb-aa8906cb71c3)

I have testd these collider

```
Collider::cuboid(1. , 1.)
Collider::cuboid(ei.width as f32 / 2., ei.height as f32 / 2)
Collider::cuboid(ei.grid.x as f32 / 2., ei.grid.y as f32 / 2.)
```

The first region work great after i set Collider::cuboid(8. , 8.), 16*16 in ldtk editor.
But the second region size strange again.

![image](https://github.com/Trouv/bevy_ecs_ldtk/assets/3898040/9fa773bc-a1a2-464a-952a-209cf8edce7e)
![image](https://github.com/Trouv/bevy_ecs_ldtk/assets/3898040/91465aaf-7a19-4c6a-996b-4527fd81d25e)

It seems ldtk entity will change Collider i created.
So i don't know what is right way to set a collider sensor for region which i want to active some game event. What should i do?

**Comment by Trouv** [comment]
My best guess for what's causing this is `bevy_ecs_ldtk`'s logic for scaling entities. It basically does `transform.scale = entity_instance_size / entity_definition_size`..

So it looks like maybe you've tried this, but what happens if you hardcode the cuboid to be half the size of the entity definition? This value specifically:
![entity_definition_size_001](https://github.com/Trouv/bevy_ecs_ldtk/assets/15664670/cd6d9f89-77a6-4d42-883e-f206289d50df)

**Comment by darkautism** [comment]
I tested this.
![image](https://github.com/Trouv/bevy_ecs_ldtk/assets/3898040/e9b23a7d-cd07-4a7d-a88a-6b0c396cd43a)
![image](https://github.com/Trouv/bevy_ecs_ldtk/assets/3898040/7553f6a1-2651-4bc7-b26e-12f3ae9bc9d4)
Only first region is fit.
![image](https://github.com/Trouv/bevy_ecs_ldtk/assets/3898040/17bf919e-5c21-4844-8efa-e7930fbce068)
![image](https://github.com/Trouv/bevy_ecs_ldtk/assets/3898040/1c40ca97-35f8-49af-b699-d0854d399a50)

![image](https://github.com/Trouv/bevy_ecs_ldtk/assets/3898040/2af83a95-23f9-4507-ab8d-a522418303f3)
![image](https://github.com/Trouv/bevy_ecs_ldtk/assets/3898040/4d03304e-559f-488f-80c7-64f446ca6267)

**Comment by Trouv** [comment]
I see - thanks for elaborating on that.

It's a very strange issue. Out of curiosity - does the collider shape change at all if you switch them? Like registering the `PlayerChatBundle` to the `ToolTips` identifier? `.register_ldtk_entity::<PlayerChatBundle>("ToolTips")`

**Comment by darkautism** [comment]
![image](https://github.com/Trouv/bevy_ecs_ldtk/assets/3898040/54501df3-c06c-437d-a02f-7780008c311f)
![image](https://github.com/Trouv/bevy_ecs_ldtk/assets/3898040/438736f0-b043-4a60-b851-a8cd95f4079b)

It seems different size have different behavior.

**Comment by Trouv** [comment]
Could you use `bevy-inspector-egui` to find out the scale of those entities? Or print them in a system? It looks like the left one is *supposed* to be (10,12,1) and the right (1,10,1),

**Comment by darkautism** [comment]
![image](https://github.com/Trouv/bevy_ecs_ldtk/assets/3898040/2a25afc7-6990-4987-bf39-960ee7f9a538)
![image](https://github.com/Trouv/bevy_ecs_ldtk/assets/3898040/e1eae9a7-ae7a-4e97-b223-ad3f6f8a8e2c)

**Comment by Trouv** [comment]
I think I have an idea of what might be happening. It looks like you might be using a `Tile` field on the `ToolTips` entity? What happens if you remove that field?

**Comment by darkautism** [comment]
![image](https://github.com/Trouv/bevy_ecs_ldtk/assets/3898040/049130b9-1a95-48ee-a403-95fa56dee877)
![image](https://github.com/Trouv/bevy_ecs_ldtk/assets/3898040/ae85b0d4-12ee-4e80-9098-090ef42a0d1a)

It seems ok if i change tooltip tile to square.

**Comment by Trouv** [comment]
#271 should fix this. I'd ask you to try it but there have been a lot of breaking changes since 0.8 that could be annoying to deal with
