### ISSUE TITLE
Implementing Chunk Loading through Levels

### ISSUE THREAD

**Issue by PraxTube** [Trouv/bevy_ecs_ldtk#268]
I am currently trying to implement chunking loading and it works fairly alright by using levels (based on [this example](https://github.com/Trouv/bevy_ecs_ldtk/blob/main/examples/level_set.rs)). However, I have to get the iids of each level in the ldtk project, which is somewhat inconvenient. Each level is a fixed size (32 x 32 tiles), so I can definitely automate this process somehow. I was just wondering if there are any other ways except the level iids to fetch a level of a ldtk project.

Perhaps this is not what ldtk is intended for in the first place, which might lead to the [XY Problem](https://en.wikipedia.org/wiki/XY_problem) here, so let me clarify what I would like to do:
I have a world that is fairly big, so I can definitely not load it all at once. Given that I have a grid world I can easily implement chunking, however this doesn't play too nicely with ldtk (at least I don't know how, which is why I am here). Is it not supposed to be used in this way? I mean I can just fetch the iids and write them into an array, but this feels like a very hacky solution.

Any advise is appreciated.

**Comment by PraxTube** [comment]
Oh wow awesome! That's exactly what I was looking for.

> I will give you this warning though. Currently, the plugin will load all of the LDtk data into memory, even the levels you don't have currently spawned, even if you are using external level files. It won't have everything spawned at once obviously - but your entire project json will be in the asset store. If you're expecting it to load level data as needed rather than just spawn as needed, that isn't the current behavior.

Yeah that makes sense. I am using a custom asset loader to preload all assets, so this is totally fine. Thanks for the warning, I will keep it in mind :) But it sounds like you plan to change this in the future?

**Comment by Trouv** [comment]
> But it sounds like you plan to change this in the future?

Very loose plans yeah. It should be doable with some of the recent refactors to the asset types. Just haven't given it enough thought to land on a good design
