### ISSUE TITLE
#[derive(LdtkEntity)] compile error: proc-macro derive produced unparseable tokens

### ISSUE THREAD

**Issue by Pixelstormer** [Trouv/bevy_ecs_ldtk#48]
Using `#[derive(LdtkEntity)]` on a type that has fields with generic type parameters causes a compile error.

Tested on Rust versions:
- 1.58.1 (db9d1b20b 2022-01-20)
- 1.60.0-nightly (6abb6385b 2022-01-26)

Tested on bevy_ecs_ldtk versions:
- 0.1
- Git main branch ([This commit](https://github.com/Trouv/bevy_ecs_ldtk/commit/048987e2ae7daae2d5ff781d13c5aaf29b068c9c) as of writing)

The error is present on all combinations of the above.

To reproduce:

1. Attempt to compile the following code:
```rust
#[allow(unused_imports)]
use bevy::prelude::*;
use bevy_ecs_ldtk::prelude::*;

#[derive(Default)]
struct Generic<T>(T);

#[allow(dead_code)]
#[derive(LdtkEntity)]
struct Entity {
    generic: Generic<u8>,
}

fn main() {}
```
2. Receive the following compile errors:
```
error: comparison operators cannot be chained
  --> src/main.rs:11:21
   |
11 |     generic: Generic<u8>,
   |                     ^  ^
   |
help: use `::<...>` instead of `<...>` to specify type or const arguments
   |
11 |     generic: Generic::<u8>,
   |                     ++

error: proc-macro derive produced unparseable tokens
 --> src/main.rs:9:10
  |
9 | #[derive(LdtkEntity)]
  |          ^^^^^^^^^^

error: could not compile `ecs-ldtk-repro` due to 2 previous errors
```

As the error above suggests, adding the `::` *does* allow the code to compile successfully, but running rustfmt will promptly remove it again (Preventing this from being a viable solution when using editors with format-on-save enabled).

**Comment by Trouv** [comment]
Thanks for bringing this up! It might be some problem with the usage of `syn` and `quote` here, but it's strange that the `::` allows it to work.

**Comment by Trouv** [comment]
I think I figured out a way around this, cheating off bevy's homework w/ its Bundle derive implementation. I need to construct it in the macro with `<#field_type as std::default::Default>::default()` rather than `#field_type::default()`
