### ISSUE TITLE
Auto-tiled IntGrid layer missing GridCoords for unset tiles

### ISSUE THREAD

**Issue by NeoRaider** [Trouv/bevy_ecs_ldtk#60]
When no auto-tile rule matches for an IntGrid cell, the generated IntGridCell entity is missing the GridCoords component. I assume that this is unintended, as the GridCoords is added correctly for non-auto-tiled IntGrid layers.

**Comment by Trouv** [comment]
Thanks for the issue!

I must not have thought of this "edge case" while developing. I have a rough idea what the problem probably is

**Comment by Trouv** [comment]
Could you see if it's fixed on the `int_grid_invisible_auto_tiles` branch?
```
bevy_ecs_ldtk = { git = "https://github.com/Trouv/bevy_ecs_ldtk", branch = "int_grid_invisible_auto_tiles" }
```

**Comment by NeoRaider** [comment]
Thanks, working perfectly! I also can't reproduce #61 anymore with that branch.

**Comment by Trouv** [comment]
(btw, I merged and deleted that branch, so you may want to change your Cargo.toml)
