### ISSUE TITLE
Ability to turn off IntGrid rendering

### ISSUE THREAD

**Issue by johanhelsing** [Trouv/bevy_ecs_ldtk#64]
Hi, It's me with the int grid issues again.

This time, I have the opposite problem as last time. I'm using IntGrid layers with my own special rendering solution and now I get "double rendering" since bevy_ecs_ldtk 0.2.

I think I could get around it by adding a mock auto-tile layer, but it would be nice with a less workaround-y way to do it.

**Comment by Trouv** [comment]
Yeah it would be easy enough to add an option to the LdtkSettings for it and just have it set the intgrid tiles to invisible, like it used to.
