### ISSUE TITLE
`set_ldtk_texture_filters_to_nearest` updates the texture every frame

### ISSUE THREAD

**Issue by oliverbestmann** [Trouv/bevy_ecs_ldtk#92]
I profiled my webassembly and realized, that bevy was uploading a large image on every frame, even if nothing happened. I tracked it down to `set_ldtk_texture_filters_to_nearest` updating the texture in https://github.com/Trouv/bevy_ecs_ldtk/blob/main/src/systems.rs#L368. The call to `get_mut` triggers a new `AssetEvent::Modified` event that will then trigger the same update in the next frame, and so on and so on.

The referenced code at https://github.com/StarArawn/bevy_ecs_tilemap/blob/main/examples/helpers/texture.rs ony looks at the `Created` event.

**Comment by Trouv** [comment]
Good catch! I remember I made it work for `Modified` as well just to try and get tileset hot reloading working w/ bevy_ecs_tilemap. However, it didn't end up working anyway, so it's probably safe to undo that change.
