### ISSUE TITLE
WASM not rendering the map

### ISSUE THREAD

**Issue by BKSalman** [Trouv/bevy_ecs_ldtk#99]
I made a simple game, and when I run the binary build the map loads just fine, 
but when I build for WASM it doesn't show the map/level 

not sure if it's a misconfiguration on my part, 

Idk what info do you need to see if it's an actual problem, 

but I will leave my [repo here](https://github.com/bksalman/t5hm) 

and feel free to ask me anything

(I'm refreshing the page here)

[scrnli_7_23_2022_3-39-03 PM.webm](https://user-images.githubusercontent.com/85521119/180605370-858ca6a4-fb4b-489f-8ff3-830e35437c14.webm)

**Comment by Trouv** [comment]
Are you using the `atlas` feature?

**Comment by BKSalman** [comment]
> Are you using the `atlas` feature?

If you are referring to the library features in the cargo file, then no...

**Comment by Trouv** [comment]
Wasm support requires using the `atlas` feature, try enabling it

**Comment by BKSalman** [comment]
> Wasm support requires using the `atlas` feature, try enabling it

oh... sorry for the unnecessary issue, should've read the main page of the repo...

**Comment by Trouv** [comment]
You're good! it could use some better visibility in the readme for sure
